language: rust
os:
  - linux
  - windows
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      export LIBCLANG_PATH="C:\\Program Files\\LLVM\\\\bin"
      export TARGET="x86_64-pc-windows-msvc"
    else
      export TARGET="x86_64-unknown-linux-gnu"
    fi
  - rustup target add "$TARGET"
  - cargo build --verbose --target "$TARGET" --all --features=bindgen 
  - cargo build --verbose --target "$TARGET" --all
  - cargo test --verbose --target "$TARGET" --all --features=bindgen 
  - cargo test --verbose --target "$TARGET" --all
  - cargo package --verbose --target "$TARGET"
deploy:
  skip_cleanup: true
  provider: cargo
  token:
    secure: qJpQ1bp5LVWN61H1kUVOyzsXIn4dZPxHkCJ2MgRpLLPlgFZvpaS/n0cSUqMoASvMhBgvj2yOma6oAZpRz3HPIIhDm724HzkWQLOHJKrRb1AVEdl2wDAJlMn8uHhyCWGr7523oGM6P8hkaURmQ3WDbXOdiOnULvnsPMTPxyMV8etwWLEPn7Sufkl1LvTC4QNk42SsJSkVMkwCtPCbp3AeghLcTDVOkMZEDcMq2mAL4gMQYR161pY0HMJyhMEVcDGQuOvtSXB8vHeHJwsq97WYLWd2l4MCyEYQQKyI7TgFV4DZxK8Ur+3CzYMhpMIUYWudXl/CrDJoidZhhXzBxtlRjfKkGmfzsOFzQzxLp85MJkx9dJ/cncx9EBxC356CNW1zw/p1mwpho5aRYs2fMtTtyw9q2j9YWSAbes7lmbJX9PkLYAQFmyf/ARwwcInhd8tFomD+WcrMD2AxxThMP5b5Ob9RbZNqVEFZi5gVRnISRAEvSFR+VSGEyLpNcWh2gQr4aTbKs9HQLhkOF7Q2dsiBT26wPftRB1lPEVBDzOnhxMZ5riwVLNahdTzz7VzOusigt9lz/eDN04V9R7k/oS6yHTKV2KVv9KkGVanj2bmhJJqrlTMWhyf+UMV1wxQiPaZeMeLbqocYzgBUe23Ka8kGEDjcYxVw1Z52o3SWiKjCSDA=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux
notifications:
  email:
    on_success: never
