[package]
name = "libftd2xx-ffi"
version = "0.1.1"
description = "Rust FFI bindings to the FTDI D2XX drivers."
keywords = ["ftdi", "ffi", "usb"]
categories = ["external-ffi-bindings"]
authors = ["Alex M."]
edition = "2018"
readme = "README.md"
build = "build.rs"
repository = "https://github.com/newAM/libftd2xx-ffi-rs/"
license = "MIT"

[build-dependencies]
bindgen = "0.54"
