[package]
name = "libftd2xx-ffi"
version = "0.1.4"  # remember to update html_root_url
description = "Rust FFI bindings to the FTDI D2XX drivers."
keywords = ["ftdi", "ffi", "usb"]
categories = ["external-ffi-bindings"]
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"
readme = "README.md"
build = "build.rs"
repository = "https://github.com/newAM/libftd2xx-ffi-rs/"
documentation = "https://docs.rs/libftd2xx-ffi"
license = "MIT"

[dependencies]
cfg-if = "0.1"

[build-dependencies]
bindgen = { version = "0.54", optional = true }
cfg-if = "0.1"

[dev-dependencies]
version-sync = "0.9"

[badges]
travis-ci = { repository = "newAM/libftd2xx-ffi-rs" }
maintenance = { status = "passively-maintained" }
